LOCAL_PATH := $(call my-dir)

# ===== Your app =====
include $(CLEAR_VARS)

LOCAL_MODULE := main
LOCAL_SHORT_COMMANDS := true

SDL_PATH := ../SDL

LOCAL_C_INCLUDES := $(LOCAL_PATH)/$(SDL_PATH)/include \
$(LOCAL_PATH)/../SDL2_mixer/include \
$(LOCAL_PATH)/common \
$(LOCAL_PATH)/../libevent/include \
$(LOCAL_PATH)/../libjpeg-turbo/include \
$(LOCAL_PATH)/../curl/include \
$(LOCAL_PATH)/../glm \
$(LOCAL_PATH)

# Add your application source files here...
LOCAL_SRC_FILES := \
    BlackWin.cpp \
    BoneManager.cpp \
    Builder.cpp \
    Button.cpp \
    CameraMove.cpp \
    CBTMessageBox.cpp \
    CComGem.cpp \
    CDirection.cpp \
    ChangeRingManager.cpp \
    CharacterManager.cpp \
    CharInfoBalloon.cpp \
    CharInfoBalloonMng.cpp \
    CharMakeWin.cpp \
    CharSelMainWin.cpp \
    CKANTURUDirection.cpp \
    CMVP1stDirection.cpp \
    CreditInfo.cpp \
    CreditWin.cpp \
    CSChaosCastle.cpp \
    CSEventMatch.cpp \
    CSItemOption.cpp \
    CSMapServer.cpp \
    CSParts.cpp \
    CSPetSystem.cpp \
    CSQuest.cpp \
    CSWaterTerrain.cpp \
    DialogInfo.cpp \
    DSplaysound.cpp \
    DSwaveIO.cpp \
    DuelMgr.cpp \
    Event.cpp \
    ExplanationInfo.cpp \
    ExternalObject/Leaf/callstackdmp.cpp \
    ExternalObject/Leaf/checkintegrity.cpp \
    ExternalObject/Leaf/ExceptionHandler.cpp \
    ExternalObject/Leaf/html_log.cpp \
    ExternalObject/Leaf/peimage.cpp \
    ExternalObject/Leaf/stdleaf.cpp \
    ExternalObject/Leaf/sysinfo.cpp \
    ExternalObject/Leaf/xortrans.cpp \
    ExternalObject/Leaf/xstreambuf.cpp \
    FilterInfo.cpp \
    FilterNameInfo.cpp \
    GambleSystem.cpp \
    GameCensorship.cpp \
    GameShop/FileDownloader/DownloadInfo.cpp \
    GameShop/FileDownloader/FileDownloader.cpp \
    GameShop/FileDownloader/FTPConnecter.cpp \
    GameShop/FileDownloader/HTTPConnecter.cpp \
    GameShop/InGameShopSystem.cpp \
    GameShop/MsgBoxIGSBuyConfirm.cpp \
    GameShop/MsgBoxIGSBuyPackageItem.cpp \
    GameShop/MsgBoxIGSBuySelectItem.cpp \
    GameShop/MsgBoxIGSCommon.cpp \
    GameShop/MsgBoxIGSDeleteItemConfirm.cpp \
    GameShop/MsgBoxIGSGiftStorageItemInfo.cpp \
    GameShop/MsgBoxIGSSendGift.cpp \
    GameShop/MsgBoxIGSSendGiftConfirm.cpp \
    GameShop/MsgBoxIGSStorageItemInfo.cpp \
    GameShop/MsgBoxIGSUseBuffConfirm.cpp \
    GameShop/MsgBoxIGSUseItemConfirm.cpp \
    GameShop/NewUIInGameShop.cpp \
    GameShop/ShopListManager/BannerInfo.cpp \
    GameShop/ShopListManager/BannerInfoList.cpp \
    GameShop/ShopListManager/BannerListManager.cpp \
    GameShop/ShopListManager/FTPFileDownLoader.cpp \
    GameShop/ShopListManager/interface/PathMethod/Path.cpp \
    GameShop/ShopListManager/interface/WZResult/WZResult.cpp \
    GameShop/ShopListManager/ListManager.cpp \
    GameShop/ShopListManager/ShopCategory.cpp \
    GameShop/ShopListManager/ShopCategoryList.cpp \
    GameShop/ShopListManager/ShopList.cpp \
    GameShop/ShopListManager/ShopListManager.cpp \
    GameShop/ShopListManager/ShopPackage.cpp \
    GameShop/ShopListManager/ShopPackageList.cpp \
    GameShop/ShopListManager/ShopProduct.cpp \
    GameShop/ShopListManager/ShopProductList.cpp \
    GameShop/ShopListManager/StringMethod.cpp \
    GameShop/ShopListManager/StringToken.cpp \
    GaugeBar.cpp \
    GIPetManager.cpp \
    GlobalBitmap.cpp \
    GM3rdChangeUp.cpp \
    GMAida.cpp \
    GMBattleCastle.cpp \
    GMCryingWolf2nd.cpp \
    GMCrywolf1st.cpp \
    GMDoppelGanger1.cpp \
    GMDoppelGanger2.cpp \
    GMDoppelGanger3.cpp \
    GMDoppelGanger4.cpp \
    GMDuelArena.cpp \
    GMEmpireGuardian1.cpp \
    GMEmpireGuardian2.cpp \
    GMEmpireGuardian3.cpp \
    GMEmpireGuardian4.cpp \
    GMHellas.cpp \
    GMHuntingGround.cpp \
    GMKarutan1.cpp \
    GMNewTown.cpp \
    GMSantaTown.cpp \
    GMSwampOfQuiet.cpp \
    GMUnitedMarketPlace.cpp \
    GM_kanturu_1st.cpp \
    GM_Kanturu_2nd.cpp \
    GM_Kanturu_3rd.cpp \
    GM_PK_Field.cpp \
    GM_Raklion.cpp \
    GOBoid.cpp \
    GuildCache.cpp \
    GuildManager.cpp \
    Input.cpp \
    ItemAddOptioninfo.cpp \
    ItemInfo.cpp \
    ItemManager.cpp \
    KeyGenerater.cpp \
    LoadData.cpp \
    LoadingScene.cpp \
    Local.cpp \
    LoginMainWin.cpp \
    LoginWin.cpp \
    MapManager.cpp \
    MatchEvent.cpp \
    Math/ZzzMathLib.cpp \
    MixMgr.cpp \
    MonkSystem.cpp \
    MoveCommandData.cpp \
    MovereqInfo.cpp \
    MovieScene.cpp \
    MsgWin.cpp \
    MultiLanguage.cpp \
    mu_2d_renderer.cpp \
    mu_sdl.cpp \
    mu_gles2_matrix.cpp \
    mu_wininet_curl_compat.cpp \
    NewBloodCastleSystem.cpp \
    NewChaosCastleSystem.cpp \
    NewUI3DRenderMng.cpp \
    NewUIBattleSoccerScore.cpp \
    NewUIBloodCastleEnter.cpp \
    NewUIBloodCastleTime.cpp \
    NewUIBuffWindow.cpp \
    NewUIButton.cpp \
    NewUICastleWindow.cpp \
    NewUICatapultWindow.cpp \
    NewUIChaosCastleTime.cpp \
    NewUICharacterInfoWindow.cpp \
    NewUIChatInputBox.cpp \
    NewUIChatLogWindow.cpp \
    NewUICommandWindow.cpp \
    NewUICommon.cpp \
    NewUICommonMessageBox.cpp \
    NewUICryWolf.cpp \
    NewUICursedTempleEnter.cpp \
    NewUICursedTempleResult.cpp \
    NewUICursedTempleSystem.cpp \
    NewUICustomMessageBox.cpp \
    NewUIDoppelGangerFrame.cpp \
    NewUIDoppelGangerWindow.cpp \
    NewUIDuelWatchMainFrameWindow.cpp \
    NewUIDuelWatchUserListWindow.cpp \
    NewUIDuelWatchWindow.cpp \
    NewUIDuelWindow.cpp \
    NewUIEmpireGuardianNPC.cpp \
    NewUIEmpireGuardianTimer.cpp \
    NewUIEnterDevilSquare.cpp \
    NewUIExchangeLuckyCoin.cpp \
    NewUIFriendWindow.cpp \
    NewUIGatemanWindow.cpp \
    NewUIGateSwitchWindow.cpp \
    NewUIGensRanking.cpp \
    NewUIGoldBowmanLena.cpp \
    NewUIGoldBowmanWindow.cpp \
    NewUIGroup.cpp \
    NewUIGuardWindow.cpp \
    NewUIGuildInfoWindow.cpp \
    NewUIGuildMakeWindow.cpp \
    NewUIHelpWindow.cpp \
    NewUIHeroPositionInfo.cpp \
    NewUIHotKey.cpp \
    NewUIInventoryCtrl.cpp \
    NewUIItemEnduranceInfo.cpp \
    NewUIItemExplanationWindow.cpp \
    NewUIItemMng.cpp \
    NewUIKanturuEvent.cpp \
    NewUILuckyItemWnd.cpp \
    NewUIMainFrameWindow.cpp \
    NewUIManager.cpp \
    NewUIMasterLevel.cpp \
    NewUIMessageBox.cpp \
    NewUIMiniMap.cpp \
    NewUIMixInventory.cpp \
    NewUIMoveCommandWindow.cpp \
    NewUIMyInventory.cpp \
    NewUIMyQuestInfoWindow.cpp \
    NewUIMyShopInventory.cpp \
    NewUINameWindow.cpp \
    NewUINPCDialogue.cpp \
    NewUINPCQuest.cpp \
    NewUINPCShop.cpp \
    NewUIOptionWindow.cpp \
    NewUIPartyInfoWindow.cpp \
    NewUIPartyListWindow.cpp \
    NewUIPetInfoWindow.cpp \
    NewUIPurchaseShopInventory.cpp \
    NewUIQuestProgress.cpp \
    NewUIQuestProgressByEtc.cpp \
    NewUIQuickCommandWindow.cpp \
    NewUIRegistrationLuckyCoin.cpp \
    NewUIRenderNumber.cpp \
    NewUIScrollBar.cpp \
    NewUISeigeWarfare.cpp \
    NewUISetItemExplanation.cpp \
    NewUISiegeWarBase.cpp \
    NewUISiegeWarCommander.cpp \
    NewUISiegeWarObserver.cpp \
    NewUISiegeWarSoldier.cpp \
    NewUISlideWindow.cpp \
    NewUIStorageInventory.cpp \
    NewUISystem.cpp \
    NewUITextBox.cpp \
    NewUITrade.cpp \
    NewUIUnitedMarketPlaceWindow.cpp \
    NewUIWindowMenu.cpp \
    npcBreeder.cpp \
    npcCatapult.cpp \
    npcGateSwitch.cpp \
    Observer.cpp \
    OptionWin.cpp \
    PartyManager.cpp \
    PersonalShopTitleImp.cpp \
    PhysicsManager.cpp \
    PList.cpp \
    PortalMgr.cpp \
    ProtectSysKey.cpp \
    ProtocolSend.cpp \
    QuestInfo.cpp \
    QuestMng.cpp \
    ServerGroup.cpp \
    ServerInfo.cpp \
    ServerListManager.cpp \
    ServerMsgWin.cpp \
    ServerSelWin.cpp \
    ShadowVolume.cpp \
    SideHair.cpp \
    SimpleModulus.cpp \
    SkillEffectMgr.cpp \
    SkillInfo.cpp \
    SkillManager.cpp \
    SlideInfo.cpp \
    Slider.cpp \
    SMD.cpp \
    SMD2BMD.cpp \
    mu_socket.cpp \
    SocketSystem.cpp \
    Sprite.cpp \
    StdAfx.cpp \
    SummonSystem.cpp \
    SysMenuWin.cpp \
    TestEventMap.cpp \
    TextureScript.cpp \
    Time/CTimCheck.cpp \
    Time/Timer.cpp \
    UIControls.cpp \
    UIDefaultBase.cpp \
    UIGateKeeper.cpp \
    UIGuardsMan.cpp \
    UIGuildInfo.cpp \
    UIGuildMaster.cpp \
    UIJewelHarmony.cpp \
    UIManager.cpp \
    UIMapName.cpp \
    UIMng.cpp \
    UIPopup.cpp \
    UISenatus.cpp \
    UIWindows.cpp \
    UsefulDef.cpp \
    Utilities/Log/DebugAngel.cpp \
    Utilities/Log/ErrorReport_Stub.cpp \
    Utilities/Log/muConsoleDebug.cpp \
    Utilities/Log/WindowsConsole.cpp \
    Utilities/Memory/MemoryLock.cpp \
    Win.cpp \
    WinEx.cpp \
    Winmain.cpp \
    WSclient.cpp \
    WSctlc.cpp \
    w_BasePet.cpp \
    w_Buff.cpp \
    w_BuffScriptLoader.cpp \
    w_BuffStateSystem.cpp \
    w_BuffStateValueControl.cpp \
    w_BuffTimeControl.cpp \
    w_CharacterInfo.cpp \
    w_CursedTemple.cpp \
    w_MapProcess.cpp \
    w_ObjectInfo.cpp \
    w_PetActionCollecter.cpp \
    w_PetActionCollecter_Add.cpp \
    w_PetActionDemon.cpp \
    w_PetActionRound.cpp \
    w_PetActionStand.cpp \
    w_PetActionUnicorn.cpp \
    w_PetProcess.cpp \
    wzAudio_SDL.cpp \
    DSPlaySound_SDL.cpp \
    ZzzAI.cpp \
    ZzzBMD.cpp \
    ZzzCharacter.cpp \
    ZzzEffect.cpp \
    ZzzEffectBlurSpark.cpp \
    ZzzEffectFireLeave.cpp \
    ZzzEffectJoint.cpp \
    ZzzEffectMagicSkill.cpp \
    ZzzEffectNoUse.cpp \
    ZzzEffectParticle.cpp \
    ZzzEffectPoint.cpp \
    ZzzEffectPointer.cpp \
    zzzeffectsprite.cpp \
    ZzzInfomation.cpp \
    ZzzInterface.cpp \
    ZzzInventory.cpp \
    ZzzLodTerrain.cpp \
    zzzMixInvetory.cpp \
    ZzzObject.cpp \
    ZzzOpenData.cpp \
    ZzzOpenglUtil.cpp \
    zzzpath.cpp \
    ZzzScene.cpp \
    ZzzTexture.cpp \
    _GlobalFunctions.cpp

LOCAL_LDLIBS := -llog -landroid -lmediandk
LOCAL_LDLIBS += -lGLESv2

LOCAL_CPP_FEATURES = exceptions

LOCAL_CFLAGS = -frtti -DANDROID -DMU_USE_SDL=1 -DUSE_LIBEVENT=1 -DMU_USE_SDL_AUDIO=1

LOCAL_CPPFLAGS += \
    -std=c++17 \
    -fexceptions \
    -frtti \
    -Wno-error \
    -Wno-error=format-security \
    -Wno-format-security


LOCAL_SHARED_LIBRARIES := SDL2 SDL2_mixer event2 curl
LOCAL_STATIC_LIBRARIES := jpeg

include $(BUILD_SHARED_LIBRARY)

$(call import-module,curl)